// @generated automatically by Diesel CLI.

/// A module containing custom SQL type definitions
///
/// (Automatically generated by Diesel.)
pub mod sql_types {
    /// The `otp_type` SQL type
    ///
    /// (Automatically generated by Diesel.)
    #[derive(diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "otp_type"))]
    pub struct OtpType;
}

diesel::table! {
    use diesel::sql_types::*;
    use super::sql_types::OtpType;

    /// Representation of the `otp` table.
    ///
    /// (Automatically generated by Diesel.)
    otp (id) {
        /// The `id` column of the `otp` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `code` column of the `otp` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        code -> Varchar,
        /// The `code_type` column of the `otp` table.
        ///
        /// Its SQL type is `OtpType`.
        ///
        /// (Automatically generated by Diesel.)
        code_type -> OtpType,
        /// The `user` column of the `otp` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        user -> Nullable<Uuid>,
    }
}

diesel::table! {
    /// Representation of the `users` table.
    ///
    /// (Automatically generated by Diesel.)
    users (user_id) {
        /// The `user_id` column of the `users` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `username` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        username -> Varchar,
        /// The `password` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        password -> Varchar,
        /// The `admin` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        admin -> Nullable<Bool>,
        /// The `blocked` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        blocked -> Nullable<Bool>,
    }
}

diesel::joinable!(otp -> users (user));

diesel::allow_tables_to_appear_in_same_query!(
    otp,
    users,
);
